// PetAlberni - Sample Data
// All placeholder data for Version 1

const categories = [
  { id: 'dogs', name: 'Dogs', icon: '🐕', count: 24, color: '#4F46E5' },
  { id: 'cats', name: 'Cats', icon: '🐈', count: 18, color: '#7C3AED' },
  { id: 'birds', name: 'Birds', icon: '🦜', count: 7, color: '#2563EB' },
  { id: 'rabbits', name: 'Rabbits', icon: '🐇', count: 5, color: '#DB2777' },
  { id: 'reptiles', name: 'Reptiles', icon: '🦎', count: 3, color: '#059669' },
  { id: 'fish', name: 'Fish', icon: '🐠', count: 9, color: '#0891B2' },
  { id: 'small-pets', name: 'Small Pets', icon: '🐹', count: 6, color: '#D97706' },
  { id: 'other', name: 'Other', icon: '🐾', count: 4, color: '#64748B' },
];

const sampleListings = [
  {
    id: 1,
    name: 'Buddy',
    type: 'Dog',
    breed: 'Golden Retriever',
    age: '3 years',
    gender: 'Male',
    description: 'Friendly and energetic Golden Retriever who loves walks along the Somass River. Great with kids and other dogs.',
    location: 'North Port Alberni',
    image: null,
    owner: 'Sarah M.',
    date: '2026-06-20',
    tags: ['friendly', 'active', 'trained'],
  },
  {
    id: 2,
    name: 'Whiskers',
    type: 'Cat',
    breed: 'Maine Coon',
    age: '2 years',
    gender: 'Female',
    description: 'A gentle indoor/outdoor cat who loves to explore. Very affectionate and good with families.',
    location: 'Downtown Alberni',
    image: null,
    owner: 'Mike T.',
    date: '2026-06-18',
    tags: ['gentle', 'affectionate', 'independent'],
  },
  {
    id: 3,
    name: 'Rocky',
    type: 'Dog',
    breed: 'German Shepherd',
    age: '5 years',
    gender: 'Male',
    description: 'Loyal and protective companion. Loves hiking on the local trails and swimming at Sproat Lake.',
    location: 'Sproat Lake Area',
    image: null,
    owner: 'Jennifer L.',
    date: '2026-06-15',
    tags: ['loyal', 'active', 'protective'],
  },
  {
    id: 4,
    name: 'Luna',
    type: 'Cat',
    breed: 'Siamese',
    age: '1 year',
    gender: 'Female',
    description: 'Playful and vocal Siamese kitten. Loves to cuddle and play with feather toys.',
    location: 'Cherry Creek',
    image: null,
    owner: 'David R.',
    date: '2026-06-22',
    tags: ['playful', 'vocal', 'cuddly'],
  },
  {
    id: 5,
    name: 'Kiwi',
    type: 'Bird',
    breed: 'Cockatiel',
    age: '4 years',
    gender: 'Male',
    description: 'Cheerful cockatiel who can whistle several tunes. Hand-raised and very social.',
    location: 'Beaver Creek',
    image: null,
    owner: 'Anna K.',
    date: '2026-06-19',
    tags: ['social', 'musical', 'hand-raised'],
  },
  {
    id: 6,
    name: 'Cinnamon',
    type: 'Rabbit',
    breed: 'Holland Lop',
    age: '1 year',
    gender: 'Female',
    description: 'Adorable floppy-eared bunny who loves to be held. Litter trained and very calm.',
    location: 'Port Alberni',
    image: null,
    owner: 'Chris P.',
    date: '2026-06-21',
    tags: ['calm', 'litter-trained', 'cuddly'],
  },
];

const lostAndFoundEntries = [
  {
    id: 1,
    type: 'lost',
    name: 'Max',
    species: 'Dog',
    breed: 'Border Collie',
    description: 'Black and white, wearing a red collar. Last seen near McLean Mill.',
    location: 'McLean Mill area',
    date: '2026-06-24',
    contact: 'Call 250-555-0123',
  },
  {
    id: 2,
    type: 'found',
    name: 'Unknown',
    species: 'Cat',
    breed: 'Tabby',
    description: 'Orange tabby found near the Paper Mill Dam Park. Very friendly, no collar.',
    location: 'Paper Mill Dam Park',
    date: '2026-06-23',
    contact: 'Call 250-555-0456',
  },
  {
    id: 3,
    type: 'lost',
    name: 'Polly',
    species: 'Bird',
    breed: 'Green Budgie',
    description: 'Small green budgie, escaped from cage. Responds to name.',
    location: 'Roger Street area',
    date: '2026-06-25',
    contact: 'Call 250-555-0789',
  },
];

const petTips = [
  {
    id: 1,
    title: 'Summer Safety for Pets',
    icon: '☀️',
    summary: 'Keep your pets cool during Alberni Valley\'s warm summers. Always provide shade and fresh water, and never leave pets in parked cars.',
    category: 'Safety',
  },
  {
    id: 2,
    title: 'Local Off-Leash Areas',
    icon: '🏞️',
    summary: 'Port Alberni has several great spots for off-leash exercise. Check the city website for designated areas and remember to clean up after your pet.',
    category: 'Activity',
  },
  {
    id: 3,
    title: 'Wildlife Awareness',
    icon: '🐻',
    summary: 'Living on Vancouver Island means encounters with wildlife. Keep pets leashed on trails and be aware of bears, cougars, and other animals.',
    category: 'Safety',
  },
  {
    id: 4,
    title: 'Vet Care in the Valley',
    icon: '🏥',
    summary: 'Regular check-ups are essential. Port Alberni has excellent veterinary clinics ready to help keep your furry friends healthy and happy.',
    category: 'Health',
  },
];

const navLinks = [
  { label: 'Home', href: '#home' },
  { label: 'Browse Pets', href: '#listings' },
  { label: 'Lost & Found', href: '#lost-found' },
  { label: 'Pet Tips', href: '#pet-tips' },
  { label: 'Add Listing', href: '#add-listing' },
];
